server:
  port: 8080
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    #link localhost
    url: jdbc:postgresql://docker-postgres-1:5432/spring-batch
    username: postgres
    password: postgres
    platform: org.hibernate.dialect.PostgreSQLDialect
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

logging:
#  level:
#    org:
#      springframework:
#        batch: DEBUG
#        batch.core: DEBUG
  file:
    path: /opt/log/app
    name: app.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
